import { googleSans } from '@/libs/font'
import type { Metadata } from 'next'
import '@/style/reset.scss'
import '@/style/global.scss'
import Header from '@/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={googleSans.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
